import type { CollaborationAsset } from './types'

export const collaborationAssets: CollaborationAsset[] = [
  {
    id: 'asset_revenue_trend',
    title: '过去 12 个完整自然月净收入趋势',
    type: 'conversation',
    status: 'active',
    businessDomain: '销售经营',
    owner: '林舟',
    updatedAt: '2026-06-23 09:18',
    description: '已保存的经营复盘会话，包含净收入趋势、默认完成订单过滤和证据入口。',
    semanticVersion: 'sales-semantic-2026.06.1',
    analysisIrVersion: 'Analysis IR 1.0',
    questionTemplate: '过去 12 个完整自然月净收入趋势',
    scope: '工作区 workspace_sales 内可见，接收者打开时重新鉴权。',
    isFavorite: true,
    isArchived: false,
    shareScope: 'workspace',
    subscriptionCadence: 'weekly',
    subscribers: 12,
    reviewers: [
      { name: '周若安', role: '指标管理员' },
      { name: '许闻舟', role: '分析师' },
    ],
    lastAudit: '2026-06-23 09:18 · share.created · watermark=on',
    watermarkedExport: true,
  },
  {
    id: 'asset_refund_rate_review',
    title: '退款率异常解释模板',
    type: 'verified_case',
    status: 'review',
    businessDomain: '客户体验',
    owner: '沈星回',
    updatedAt: '2026-06-22 18:42',
    description: '候选案例，保存问题模板、IR、语义版本和适用范围，等待分析师审核后进入资产库。',
    semanticVersion: 'cx-semantic-2026.06.0-rc1',
    analysisIrVersion: 'Analysis IR 1.0',
    questionTemplate: '解释上周退款率异常升高的主要驱动因素',
    scope: '仅审核人和创建者可见，未审核前不可订阅。',
    isFavorite: false,
    isArchived: false,
    shareScope: 'private',
    subscriptionCadence: 'none',
    subscribers: 0,
    reviewers: [
      { name: '许闻舟', role: '分析师' },
    ],
    lastAudit: '2026-06-22 18:42 · case.submitted · pii_scan=pass',
    watermarkedExport: false,
  },
  {
    id: 'asset_region_rank',
    title: '区域经营周报订阅',
    type: 'subscription',
    status: 'active',
    businessDomain: '销售经营',
    owner: '经营分析组',
    updatedAt: '2026-06-23 08:00',
    description: '每周一 08:00 生成区域收入、订单数和退款率摘要，发送给授权业务负责人。',
    semanticVersion: 'sales-semantic-2026.06.1',
    analysisIrVersion: 'Analysis IR 1.0',
    questionTemplate: '按区域汇总上周经营核心指标并标记异常',
    scope: '区域负责人仅能看到自己授权区域，通知不携带明细行。',
    isFavorite: false,
    isArchived: false,
    shareScope: 'domain_leads',
    subscriptionCadence: 'weekly',
    subscribers: 26,
    reviewers: [
      { name: '周若安', role: '指标管理员' },
      { name: '安全管理员', role: '安全复核' },
    ],
    lastAudit: '2026-06-23 08:00 · subscription.sent · recipients=26',
    watermarkedExport: true,
  },
  {
    id: 'asset_channel_aov',
    title: '各渠道客单价对比',
    type: 'template',
    status: 'archived',
    businessDomain: '销售经营',
    owner: '赵清越',
    updatedAt: '2026-06-12 14:33',
    description: '旧版渠道分析模板，因渠道枚举调整已归档，保留审计和历史分享记录。',
    semanticVersion: 'sales-semantic-2026.04.1',
    analysisIrVersion: 'Analysis IR 1.0',
    questionTemplate: '对比各渠道过去 90 天客单价',
    scope: '已归档，仅所有者和管理员可恢复。',
    isFavorite: false,
    isArchived: true,
    shareScope: 'external_blocked',
    subscriptionCadence: 'none',
    subscribers: 0,
    reviewers: [
      { name: '赵清越', role: '财务数据组' },
    ],
    lastAudit: '2026-06-12 14:33 · asset.archived · reason=enum_changed',
    watermarkedExport: true,
  },
]

