import type { DataSource } from './types'

export const dataSources: DataSource[] = [
  {
    id: 'warehouse_sales',
    name: '经营数仓 / 销售主题域',
    engine: 'Snowflake',
    businessDomain: '销售经营',
    status: 'healthy',
    connection: '只读服务账号 · cn_sales_reader',
    lastSyncAt: '2026-06-23 08:04',
    nextSyncAt: '2026-06-24 08:00',
    freshness: '1 小时 12 分钟',
    owner: '数据平台组',
    credentialRef: 'vault://prod/snowflake/sales-reader',
    scannedTables: 42,
    classifiedFields: 318,
    qualityScore: 98,
    scanBudget: '每日 08:00 · 最大 5 GB 元数据扫描',
    qualityGates: [
      { name: '连通性', status: 'pass', value: '238ms', target: '< 1s', detail: '查询网关可访问，只读凭据有效。' },
      { name: '新鲜度', status: 'pass', value: '1h12m', target: '< 4h', detail: '核心事实表已在 SLA 内完成同步。' },
      { name: '字段分类', status: 'pass', value: '100%', target: '100%', detail: '受限字段已标记并继承脱敏策略。' },
      { name: '枚举完整性', status: 'warning', value: '96%', target: '98%', detail: '渠道枚举有 2 个低频值待确认。' },
    ],
    syncEvents: [
      { at: '08:04', status: 'success', summary: '同步 42 张表、318 个字段、18 个枚举。' },
      { at: '07:58', status: 'success', summary: '连接测试通过，扫描预算使用 1.8 GB。' },
      { at: '昨天 08:06', status: 'warning', summary: '渠道枚举低频值进入待确认队列。' },
    ],
    tables: [
      {
        id: 'dwd_order_settlement',
        name: 'dwd_order_settlement',
        displayName: '订单结算事实表',
        rowCount: '1.28B',
        freshness: '2026-06-23 08:00',
        owner: '销售数据组',
        qualityScore: 99,
        columns: [
          { name: 'completed_order_id', type: 'varchar', nullable: false, classification: 'internal', description: '完成订单主键', samplePolicy: '可用于聚合，不可导出明细' },
          { name: 'net_revenue', type: 'decimal(18,2)', nullable: false, classification: 'confidential', description: '扣除退款和税费后的净收入', samplePolicy: '聚合可见，明细脱敏' },
          { name: 'customer_phone', type: 'varchar', nullable: true, classification: 'restricted', description: '客户手机号', samplePolicy: '默认不可见，不参与候选值展示' },
          { name: 'order_date', type: 'date', nullable: false, classification: 'public', description: '订单自然日', samplePolicy: '可用于筛选与分组' },
        ],
      },
      {
        id: 'dim_sales_region',
        name: 'dim_sales_region',
        displayName: '销售区域维表',
        rowCount: '4.2K',
        freshness: '2026-06-23 07:45',
        owner: '销售运营组',
        qualityScore: 97,
        columns: [
          { name: 'region_id', type: 'varchar', nullable: false, classification: 'internal', description: '区域 ID', samplePolicy: '可 join，不展示给业务用户' },
          { name: 'region_name', type: 'varchar', nullable: false, classification: 'public', description: '区域名称', samplePolicy: '可展示候选值' },
          { name: 'manager_user_id', type: 'varchar', nullable: true, classification: 'confidential', description: '区域负责人账号', samplePolicy: '仅管理员可见' },
        ],
      },
    ],
  },
  {
    id: 'warehouse_finance',
    name: '财务核算库',
    engine: 'PostgreSQL',
    businessDomain: '财务核算',
    status: 'degraded',
    connection: '只读服务账号 · finance_reader',
    lastSyncAt: '2026-06-22 23:10',
    nextSyncAt: '2026-06-23 23:00',
    freshness: '9 小时 04 分钟',
    owner: '财务数据组',
    credentialRef: 'vault://prod/postgres/finance-reader',
    scannedTables: 18,
    classifiedFields: 126,
    qualityScore: 91,
    scanBudget: '每日 23:00 · 最大 1 GB 元数据扫描',
    qualityGates: [
      { name: '连通性', status: 'pass', value: '412ms', target: '< 1s', detail: '凭据有效，连接池可用。' },
      { name: '新鲜度', status: 'warning', value: '9h04m', target: '< 8h', detail: '凭证表同步延迟，可信答案会展示新鲜度提示。' },
      { name: '字段分类', status: 'pass', value: '100%', target: '100%', detail: '财务敏感字段已标记。' },
      { name: '空值率', status: 'warning', value: '3.8%', target: '< 2%', detail: '发票来源字段缺失率升高。' },
    ],
    syncEvents: [
      { at: '23:10', status: 'warning', summary: '同步完成，发票来源字段空值率高于门禁。' },
      { at: '23:01', status: 'success', summary: '连接测试通过。' },
      { at: '昨天 23:08', status: 'success', summary: '同步 18 张表、126 个字段。' },
    ],
    tables: [
      {
        id: 'fct_invoice',
        name: 'fct_invoice',
        displayName: '发票事实表',
        rowCount: '86.4M',
        freshness: '2026-06-22 23:00',
        owner: '财务数据组',
        qualityScore: 91,
        columns: [
          { name: 'invoice_id', type: 'varchar', nullable: false, classification: 'internal', description: '发票 ID', samplePolicy: '可用于聚合' },
          { name: 'invoice_amount', type: 'decimal(18,2)', nullable: false, classification: 'confidential', description: '发票金额', samplePolicy: '聚合可见，明细需审批' },
          { name: 'taxpayer_id', type: 'varchar', nullable: false, classification: 'restricted', description: '纳税人识别号', samplePolicy: '默认不可见' },
        ],
      },
    ],
  },
  {
    id: 'lake_behavior',
    name: '用户行为湖仓',
    engine: 'ClickHouse',
    businessDomain: '用户增长',
    status: 'syncing',
    connection: '只读服务账号 · growth_events_reader',
    lastSyncAt: '同步中',
    nextSyncAt: '增量每 30 分钟',
    freshness: '同步中',
    owner: '增长数据组',
    credentialRef: 'vault://prod/clickhouse/growth-reader',
    scannedTables: 63,
    classifiedFields: 492,
    qualityScore: 95,
    scanBudget: '每 30 分钟 · 最大 2 GB 增量扫描',
    qualityGates: [
      { name: '连通性', status: 'pass', value: '188ms', target: '< 1s', detail: '连接正常。' },
      { name: '增量扫描', status: 'warning', value: '运行中', target: '< 12m', detail: '事件分区正在扫描，完成前不进入可信答案。' },
      { name: '字段分类', status: 'pass', value: '100%', target: '100%', detail: '设备标识符已按受限字段处理。' },
    ],
    syncEvents: [
      { at: '09:02', status: 'warning', summary: '增量扫描仍在运行。' },
      { at: '08:32', status: 'success', summary: '上一批增量同步完成。' },
    ],
    tables: [
      {
        id: 'events_app_session',
        name: 'events_app_session',
        displayName: 'App 会话事件',
        rowCount: '3.6B',
        freshness: '同步中',
        owner: '增长数据组',
        qualityScore: 95,
        columns: [
          { name: 'session_id', type: 'String', nullable: false, classification: 'internal', description: '会话 ID', samplePolicy: '可用于去重计数' },
          { name: 'device_id', type: 'String', nullable: false, classification: 'restricted', description: '设备标识符', samplePolicy: '默认不可见' },
          { name: 'event_time', type: 'DateTime', nullable: false, classification: 'public', description: '事件时间', samplePolicy: '可用于时间筛选' },
        ],
      },
    ],
  },
]
